baseURL: https://zpc2222.github.io # 绑定的域名
languageCode: zh-cn # en-us
title: 我的个人小站
theme: PaperMod  # 主题名字，和themes文件夹下的一致

enableInlineShortcodes: true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true
hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics:  # 谷歌统计
# Copyright: 藏锋

paginate: 15    # 首页每页显示的文章数

minify:
    disableXML: true
    # minifyOutput: true

permalinks: # 访问博客时网址的显示形式
  post: "/:title/"
  # post: "/:year/:month/:day/:title/"

defaultContentLanguage: en # 最顶部首先展示的语言页面
defaultContentLanguageInSubdir: true

languages:
    en:
      languageName: "English"
      weight: 1
      profileMode:
        enabled: true
        title: (〃'▽'〃)
        subtitle: 
        subtitle: "🧨人生三大真理：<br/>暴力真的可以解决一切，<br/>帅真的可以当饭吃，<br/>有钱真的可以为所欲为。<br/>"
        imageUrl: "img/wangzhan.jpg"
        imageTitle: 
        imageWidth: 150
        imageHeight: 150
        buttons:
          - name: 🧱 博客
            url: posts/blog
          - name: 👨🏻‍💻 技术
            url: posts/tech
          - name: 📕 阅读
            url: posts/read
          - name: ☕ 生活
            url: posts/life   
          - name: 🛠️ 工具
            url: posts/tools
      menu:
        main:
          - identifier: search
            name: 🔍 搜索
            url: search
            weight: 1
          - identifier: home
            name: 🏠 主页
            url: /
            weight: 2
          - identifier: posts
            name: 📚 文章
            url: posts
            weight: 3
          - identifier: tags
            name: 🧩 标签
            url: tags
            weight: 15
          - identifier: archives
            name: ⏱ 时间轴
            url: archives/
            weight: 20
          - identifier: about
            name: 🙋🏻‍♂️ 关于
            url: about
            weight: 50
          - identifier: links
            name: 🤝 友链
            url: links
            weight: 60

outputs:
    home:
        - HTML
        - RSS
        - JSON

# 这里的参数会被代码以 .Site.Params 的形式读取
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: ""
    author: 藏锋
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto  # defaultTheme: light or  dark 
    disableThemeToggle: false
    DateFormat: "2006-01-02"
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecialistPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    hideFooter: false # 隐藏页脚
    ShowWordCounts: true
    VisitCount: true
    ShowLastMod: true #显示文章更新时间

    ShowToc: true # 显示目录
    TocOpen: true # 自动展开目录

    comments: true
    socialIcons:
        - name: github
          url: "https://github.com/zpc2222"
        - name: QQ
          url: "img/qq.jpg"
        - name: WeChat
          url: "img/wx.jpg"
        - name: email
          url: "mailto:mozhou2222@gmail.com"
        - name: RSS
          url: "index.xml"

    label:
        text: "我的个人小站"
        icon: "img/Q.gif"
        iconHeight: 35

    analytics:
        google:
            SiteVerificationTag: ""

    assets:
        favicon: "img/Q.gif"
        favicon16x16: "img/Q.gif"
        favicon32x32: "img/Q.gif"
        apple_touch_icon: "img/Q.gif"
        safari_pinned_tab: "img/Q.gif"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary"]

    Reward: true #打赏是否开启
    # 打赏微信图片地址，
    # 可用绝对和相对地址，相对地址的图片需放在static/img下，
    # 填写格式为img/wechat_pay.png
    WechatPay: img/wechat-pay.jpg
    Alipay: img/ali-pay.jpg #打赏支付宝图片地址

    # twikoo评论
    twikoo:
      version: 1.5.8
      id:  # 填写自己的twikoo id
      region:  # 环境地域，默认为 ap-shanghai，如果您的环境地域不是上海，需传此参数，请看twikoo官方文档

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话
    highlight:
        # anchorLineNos: true
        codeFences: true  
        guessSyntax: true
        lineNos: true
        noClasses: true
        tabWidth: 4
        style: monokai
        # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
        # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
        # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
        # lineNoStart：行号从编号几开始，一般从 1 开始。
        # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.
        # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.
        # noClasses：使用 class 标签，而不是内嵌的内联样式

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
        